services:
  api:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "${UVICORN_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./poetry.lock
