# Docker Compose configuration for development environment

x-api-common: &api-common
  build:
    context: ..
    dockerfile: infra/docker/dev.Dockerfile
  env_file:
    - .env
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONUNBUFFERED=1
    - MONGO_URI=mongodb://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@ferretdb:27017
    - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME:-ers}
  restart: unless-stopped
  depends_on:
    ferretdb:
      condition: service_healthy
  develop:
    watch:
      - action: sync
        path: ../src
        target: /app/src
      - action: rebuild
        path: ../pyproject.toml
      - action: rebuild
        path: ../poetry.lock
  networks:
    - local

services:
  curation-api:
    <<: *api-common
    container_name: "curation-api"
    command: ["/scripts/start-curation-api.sh"]
    ports:
      - "${UVICORN_PORT:-8000}:8000"
    environment:
      - SEED_DB=true  # for development only

  ers-api:
    <<: *api-common
    container_name: "ers-api"
    command: ["/scripts/start-ers-api.sh"]
    ports:
      - "${ERS_API_PORT:-8001}:8001"

  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0-ferretdb-2.7.0
    restart: on-failure
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-username}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ../data:/var/lib/postgresql/data
    networks:
      - local

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.7.0
    restart: on-failure
    container_name: "ferretdb"
    ports:
      - "27017:27017"
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-postgres}
    depends_on:
      - postgres
    networks:
      - local

networks:
  local:
